version: '2.1'
services:
  rabbitmq: 
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: "exit 0"
  api:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
  someservice:
    build: ./some-service
    depends_on:
      rabbitmq:
        condition: service_healthy
      api:
        condition: service_started